//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myproject_Hotel_booking_system
{
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        [Key]
        public int userId { get; set; }
        [Required(ErrorMessage = "First name required")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Last name required")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "Email required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Password required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Please retype password mismatch")]
        [DataType(DataType.Password)]
        public string confirmPassword { get; set; }
        [Required(ErrorMessage = "Username required")]
        public string userName { get; set; }
    }
}
